import { NextRequest, NextResponse } from 'next/server'
import { getPool } from '@/lib/db'
import { executeBatch } from '@/lib/sql'

const dropScript = `
DROP TABLE IF EXISTS AVALIACAORESPOSTA CASCADE;
DROP TABLE IF EXISTS RESPOSTA CASCADE;
DROP TABLE IF EXISTS DUVIDA CASCADE;
DROP TABLE IF EXISTS MATERIA CASCADE;
DROP TABLE IF EXISTS PERIODO CASCADE;
DROP TABLE IF EXISTS CURSO CASCADE;
DROP TABLE IF EXISTS USUARIOADMINISTRADOR CASCADE;
DROP TABLE IF EXISTS USUARIO CASCADE;
DROP TABLE IF EXISTS PERMISSAOUSUARIO CASCADE;
`

const createScript = `
-- 1. PERMISSAOUSUARIO
CREATE TABLE PERMISSAOUSUARIO (
  PU_IDPERMISSAO SERIAL PRIMARY KEY,
  PU_NOMEPERMISSAO VARCHAR(80) NOT NULL UNIQUE,
  PU_POSTARDUVIDA BOOLEAN NOT NULL DEFAULT FALSE,
  PU_RESPONDERDUVIDA BOOLEAN NOT NULL DEFAULT FALSE,
  PU_AVALIARRESPOSTA BOOLEAN NOT NULL DEFAULT FALSE,
  PU_ATIVO BOOLEAN NOT NULL DEFAULT TRUE
);

-- 2. CURSO
CREATE TABLE CURSO (
  CUR_ID SERIAL PRIMARY KEY,
  CUR_DESC VARCHAR(80) NOT NULL UNIQUE,
  CUR_ATIVO BOOLEAN NOT NULL DEFAULT TRUE
);

-- 3. PERIODO
CREATE TABLE PERIODO (
  PER_ID SERIAL PRIMARY KEY,
  PER_DESCRICAO VARCHAR(50) NOT NULL UNIQUE,
  PER_ATIVO BOOLEAN NOT NULL DEFAULT TRUE
);

-- 4. MATERIA
CREATE TABLE MATERIA (
  MAT_ID SERIAL PRIMARY KEY,
  MAT_IDCURSO INT NOT NULL,
  MAT_IDPERIODO INT NOT NULL,
  MAT_DESC VARCHAR(100) NOT NULL,
  MAT_DESCRICAOCONTEUDO TEXT,
  CONSTRAINT FK_MATERIA_CURSO FOREIGN KEY (MAT_IDCURSO)
    REFERENCES CURSO(CUR_ID)
    ON DELETE NO ACTION,
  CONSTRAINT FK_MATERIA_PERIODO FOREIGN KEY (MAT_IDPERIODO)
    REFERENCES PERIODO(PER_ID)
    ON DELETE NO ACTION
);

-- 5. USUARIO
CREATE TABLE USUARIO (
  USU_ID BIGSERIAL PRIMARY KEY,
  USU_IDPERMISSAO INT NOT NULL,
  USU_MATRICULA BIGINT NOT NULL UNIQUE,
  USU_NOME VARCHAR(150) NOT NULL,
  USU_CPF CHAR(11) NOT NULL UNIQUE,
  USU_SENHA BYTEA NOT NULL,
  USU_EMAIL VARCHAR(100) NOT NULL UNIQUE,
  USU_ATIVO BOOLEAN NOT NULL DEFAULT TRUE,
  USU_AVALIACAO NUMERIC(3,2),
  CONSTRAINT FK_USUARIO_PERMISSAO FOREIGN KEY (USU_IDPERMISSAO)
    REFERENCES PERMISSAOUSUARIO(PU_IDPERMISSAO)
    ON DELETE NO ACTION
);

-- 6. USUARIOADMINISTRADOR
CREATE TABLE USUARIOADMINISTRADOR (
  USRADM_IDUSUARIO BIGINT PRIMARY KEY,
  USRADM_EXCLUIRPERGUNTA BOOLEAN NOT NULL DEFAULT TRUE,
  USRADM_EXCLUIRRESPOSTA BOOLEAN NOT NULL DEFAULT TRUE,
  USRADM_ATIVO BOOLEAN NOT NULL DEFAULT TRUE,
  CONSTRAINT FK_USUARIOADMINISTRADOR_USUARIO FOREIGN KEY (USRADM_IDUSUARIO)
    REFERENCES USUARIO(USU_ID)
    ON DELETE CASCADE
);

-- 7. DUVIDA
CREATE TABLE DUVIDA (
  DUV_IDDUVIDA SERIAL PRIMARY KEY,
  DUV_IDUSUARIO BIGINT NOT NULL,
  DUV_IDMATERIA INT NOT NULL,
  DUV_DATADUVIDA TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  DUV_TITULO VARCHAR(200) NOT NULL,
  DUV_DESCRICAO TEXT NOT NULL,
  DUV_RESOLVIDA BOOLEAN NOT NULL DEFAULT FALSE,
  CONSTRAINT FK_DUVIDA_USUARIO FOREIGN KEY (DUV_IDUSUARIO)
    REFERENCES USUARIO(USU_ID)
    ON DELETE NO ACTION,
  CONSTRAINT FK_DUVIDA_MATERIA FOREIGN KEY (DUV_IDMATERIA)
    REFERENCES MATERIA(MAT_ID)
    ON DELETE NO ACTION
);

-- 8. RESPOSTA
CREATE TABLE RESPOSTA (
  RES_IDRESPOSTA SERIAL PRIMARY KEY,
  RES_IDDUVIDA INT NOT NULL,
  RES_IDUSUARIO BIGINT NOT NULL,
  RES_DATARESPOSTA TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  RES_DESCRICAO TEXT NOT NULL,
  RES_MELHORRESPOSTA BOOLEAN NOT NULL DEFAULT FALSE,
  CONSTRAINT FK_RESPOSTA_DUVIDA FOREIGN KEY (RES_IDDUVIDA)
    REFERENCES DUVIDA(DUV_IDDUVIDA)
    ON DELETE CASCADE,
  CONSTRAINT FK_RESPOSTA_USUARIO FOREIGN KEY (RES_IDUSUARIO)
    REFERENCES USUARIO(USU_ID)
    ON DELETE NO ACTION
);

-- 9. AVALIACAORESPOSTA
CREATE TABLE AVALIACAORESPOSTA (
  AVA_ID SERIAL PRIMARY KEY,
  AVA_IDRESPOSTA INT NOT NULL,
  AVA_IDUSUARIO BIGINT NOT NULL,
  AVA_ESTRELA SMALLINT NOT NULL,
  CONSTRAINT FK_AVALIACAORESPOSTA_RESPOSTA FOREIGN KEY (AVA_IDRESPOSTA)
    REFERENCES RESPOSTA(RES_IDRESPOSTA)
    ON DELETE CASCADE,
  CONSTRAINT FK_AVALIACAORESPOSTA_USUARIO FOREIGN KEY (AVA_IDUSUARIO)
    REFERENCES USUARIO(USU_ID)
    ON DELETE NO ACTION,
  CONSTRAINT UQ_AVALIACAO_USUARIO_RESPOSTA UNIQUE (AVA_IDRESPOSTA, AVA_IDUSUARIO),
  CONSTRAINT CK_AVALIACAO_ESTRELA_RANGE CHECK (AVA_ESTRELA >= 1 AND AVA_ESTRELA <= 5)
);

-- INDEXES
CREATE INDEX IDX_USUARIO_IDPERMISSAO ON USUARIO(USU_IDPERMISSAO);
CREATE INDEX IDX_MATERIA_IDCURSO ON MATERIA(MAT_IDCURSO);
CREATE INDEX IDX_MATERIA_IDPERIODO ON MATERIA(MAT_IDPERIODO);
CREATE INDEX IDX_DUVIDA_IDUSUARIO ON DUVIDA(DUV_IDUSUARIO);
CREATE INDEX IDX_DUVIDA_IDMATERIA ON DUVIDA(DUV_IDMATERIA);
CREATE INDEX IDX_RESPOSTA_IDDUVIDA ON RESPOSTA(RES_IDDUVIDA);
CREATE INDEX IDX_RESPOSTA_IDUSUARIO ON RESPOSTA(RES_IDUSUARIO);
CREATE INDEX IDX_AVALIACAORESPOSTA_IDUSUARIO ON AVALIACAORESPOSTA(AVA_IDUSUARIO);
CREATE INDEX IDX_USUARIO_NOME ON USUARIO(USU_NOME);
CREATE INDEX IDX_DUVIDA_DATA ON DUVIDA(DUV_DATADUVIDA DESC);
CREATE INDEX IDX_MATERIA_DESC ON MATERIA(MAT_DESC);
`

export async function POST(req: NextRequest) {
	try {
		const url = new URL(req.url)
		const drop = url.searchParams.get('drop') === 'true'
		const pool = await getPool()
		
		const client = await pool.connect()
		try {
			await client.query('BEGIN')
			
			if (drop) {
				await executeBatch(dropScript)
			}
			await executeBatch(createScript)
			
			await client.query('COMMIT')
			return NextResponse.json({ ok: true, dropped: drop, created: true })
		} catch (e) {
			await client.query('ROLLBACK')
			throw e
		} finally {
			client.release()
		}
	} catch (err) {
		return NextResponse.json({ ok: false, error: (err as Error).message }, { status: 500 })
	}
}

