import { NextRequest, NextResponse } from 'next/server'
import { getPool } from '@/lib/db'
import { executeBatch } from '@/lib/sql'

const dropScript = `
DROP TABLE IF EXISTS AVALIACAORESPOSTA;
DROP TABLE IF EXISTS RESPOSTA;
DROP TABLE IF EXISTS DUVIDA;
DROP TABLE IF EXISTS MATERIA;
DROP TABLE IF EXISTS PERIODO;
DROP TABLE IF EXISTS CURSO;
DROP TABLE IF EXISTS USUARIOADMINISTRADOR;
DROP TABLE IF EXISTS USUARIO;
DROP TABLE IF EXISTS PERMISSAOUSUARIO;
GO
`

const createScript = `
-- 1. PERMISSAOUSUARIO
CREATE TABLE PERMISSAOUSUARIO (
  PU_IDPERMISSAO INT IDENTITY(0,1) PRIMARY KEY,
  PU_NOMEPERMISSAO VARCHAR(80) NOT NULL UNIQUE,
  PU_POSTARDUVIDA BIT NOT NULL DEFAULT 0,
  PU_RESPONDERDUVIDA BIT NOT NULL DEFAULT 0,
  PU_AVALIARRESPOSTA BIT NOT NULL DEFAULT 0,
  PU_ATIVO BIT NOT NULL DEFAULT 1
);
GO
-- 2. CURSO
CREATE TABLE CURSO (
  CUR_ID INT IDENTITY(0,1) PRIMARY KEY,
  CUR_DESC VARCHAR(80) NOT NULL UNIQUE,
  CUR_ATIVO BIT NOT NULL DEFAULT 1
);
GO
-- 3. PERIODO
CREATE TABLE PERIODO (
  PER_ID INT IDENTITY(1,1) PRIMARY KEY,
  PER_DESCRICAO VARCHAR(50) NOT NULL UNIQUE,
  PER_ATIVO BIT NOT NULL DEFAULT 1
);
GO
-- 4. MATERIA
CREATE TABLE MATERIA (
  MAT_ID INT IDENTITY(1,1) PRIMARY KEY,
  MAT_IDCURSO INT NOT NULL,
  MAT_IDPERIODO INT NOT NULL,
  MAT_DESC VARCHAR(100) NOT NULL,
  MAT_DESCRICAOCONTEUDO VARCHAR(MAX),
  CONSTRAINT FK_MATERIA_CURSO FOREIGN KEY (MAT_IDCURSO)
    REFERENCES CURSO(CUR_ID)
    ON DELETE NO ACTION,
  CONSTRAINT FK_MATERIA_PERIODO FOREIGN KEY (MAT_IDPERIODO)
    REFERENCES PERIODO(PER_ID)
    ON DELETE NO ACTION
);
GO
-- 5. USUARIO
CREATE TABLE USUARIO (
  USU_ID BIGINT IDENTITY(1,1) PRIMARY KEY,
  USU_IDPERMISSAO INT NOT NULL,
  USU_MATRICULA BIGINT NOT NULL UNIQUE,
  USU_NOME VARCHAR(150) NOT NULL,
  USU_CPF CHAR(11) NOT NULL UNIQUE,
  USU_SENHA VARBINARY(64) NOT NULL,
  USU_EMAIL VARCHAR(100) NOT NULL UNIQUE,
  USU_ATIVO BIT NOT NULL DEFAULT 1,
  CONSTRAINT FK_USUARIO_PERMISSAO FOREIGN KEY (USU_IDPERMISSAO)
    REFERENCES PERMISSAOUSUARIO(PU_IDPERMISSAO)
    ON DELETE NO ACTION
);
GO
-- 6. USUARIOADMINISTRADOR
CREATE TABLE USUARIOADMINISTRADOR (
  USRADM_IDUSUARIO BIGINT PRIMARY KEY,
  USRADM_EXCLUIRPERGUNTA BIT NOT NULL DEFAULT 1,
  USRADM_EXCLUIRRESPOSTA BIT NOT NULL DEFAULT 1,
  USRADM_ATIVO BIT NOT NULL DEFAULT 1,
  CONSTRAINT FK_USUARIOADMINISTRADOR_USUARIO FOREIGN KEY (USRADM_IDUSUARIO)
    REFERENCES USUARIO(USU_ID)
    ON DELETE CASCADE
);
GO
-- 7. DUVIDA
CREATE TABLE DUVIDA (
  DUV_IDDUVIDA INT IDENTITY(1,1) PRIMARY KEY,
  DUV_IDUSUARIO BIGINT NOT NULL,
  DUV_IDMATERIA INT NOT NULL,
  DUV_DATADUVIDA DATETIME NOT NULL DEFAULT GETDATE(),
  DUV_TITULO VARCHAR(200) NOT NULL,
  DUV_DESCRICAO VARCHAR(MAX) NOT NULL,
  DUV_RESOLVIDA BIT NOT NULL DEFAULT 0,
  CONSTRAINT FK_DUVIDA_USUARIO FOREIGN KEY (DUV_IDUSUARIO)
    REFERENCES USUARIO(USU_ID)
    ON DELETE NO ACTION,
  CONSTRAINT FK_DUVIDA_MATERIA FOREIGN KEY (DUV_IDMATERIA)
    REFERENCES MATERIA(MAT_ID)
    ON DELETE NO ACTION
);
GO
-- 8. RESPOSTA
CREATE TABLE RESPOSTA (
  RES_IDRESPOSTA INT IDENTITY(1,1) PRIMARY KEY,
  RES_IDDUVIDA INT NOT NULL,
  RES_IDUSUARIO BIGINT NOT NULL,
  RES_DATARESPOSTA DATETIME NOT NULL DEFAULT GETDATE(),
  RES_DESCRICAO VARCHAR(MAX) NOT NULL,
  RES_MELHORRESPOSTA BIT NOT NULL DEFAULT 0,
  CONSTRAINT FK_RESPOSTA_DUVIDA FOREIGN KEY (RES_IDDUVIDA)
    REFERENCES DUVIDA(DUV_IDDUVIDA)
    ON DELETE CASCADE,
  CONSTRAINT FK_RESPOSTA_USUARIO FOREIGN KEY (RES_IDUSUARIO)
    REFERENCES USUARIO(USU_ID)
    ON DELETE NO ACTION
);
GO
-- 9. AVALIACAORESPOSTA
CREATE TABLE AVALIACAORESPOSTA (
  AVA_ID INT IDENTITY(1,1) PRIMARY KEY,
  AVA_IDRESPOSTA INT NOT NULL,
  AVA_IDUSUARIO BIGINT NOT NULL,
  AVA_ESTRELA TINYINT NOT NULL,
  CONSTRAINT FK_AVALIACAORESPOSTA_RESPOSTA FOREIGN KEY (AVA_IDRESPOSTA)
    REFERENCES RESPOSTA(RES_IDRESPOSTA)
    ON DELETE CASCADE,
  CONSTRAINT FK_AVALIACAORESPOSTA_USUARIO FOREIGN KEY (AVA_IDUSUARIO)
    REFERENCES USUARIO(USU_ID)
    ON DELETE NO ACTION,
  CONSTRAINT UQ_AVALIACAO_USUARIO_RESPOSTA UNIQUE (AVA_IDRESPOSTA, AVA_IDUSUARIO),
  CONSTRAINT CK_AVALIACAO_ESTRELA_RANGE CHECK (AVA_ESTRELA >= 1 AND AVA_ESTRELA <= 5)
);
GO
-- INDEXES
CREATE INDEX IDX_USUARIO_IDPERMISSAO ON USUARIO(USU_IDPERMISSAO);
CREATE INDEX IDX_MATERIA_IDCURSO ON MATERIA(MAT_IDCURSO);
CREATE INDEX IDX_MATERIA_IDPERIODO ON MATERIA(MAT_IDPERIODO);
CREATE INDEX IDX_DUVIDA_IDUSUARIO ON DUVIDA(DUV_IDUSUARIO);
CREATE INDEX IDX_DUVIDA_IDMATERIA ON DUVIDA(DUV_IDMATERIA);
CREATE INDEX IDX_RESPOSTA_IDDUVIDA ON RESPOSTA(RES_IDDUVIDA);
CREATE INDEX IDX_RESPOSTA_IDUSUARIO ON RESPOSTA(RES_IDUSUARIO);
CREATE INDEX IDX_AVALIACAORESPOSTA_IDUSUARIO ON AVALIACAORESPOSTA(AVA_IDUSUARIO);
CREATE INDEX IDX_USUARIO_NOME ON USUARIO(USU_NOME);
CREATE INDEX IDX_DUVIDA_DATA ON DUVIDA(DUV_DATADUVIDA DESC);
CREATE INDEX IDX_MATERIA_DESC ON MATERIA(MAT_DESC);
GO
`

export async function POST(req: NextRequest) {
	try {
		const url = new URL(req.url)
		const drop = url.searchParams.get('drop') === 'true'
		const pool = await getPool()
		const tx = pool.transaction()
		await tx.begin()
		try {
			if (drop) {
				await executeBatch(dropScript)
			}
			await executeBatch(createScript)
			await tx.commit()
			return NextResponse.json({ ok: true, dropped: drop, created: true })
		} catch (e) {
			await tx.rollback()
			throw e
		}
	} catch (err) {
		return NextResponse.json({ ok: false, error: (err as Error).message }, { status: 500 })
	}
}

